# Generated by Django 4.1.5 on 2023-01-06 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date_time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='task',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
