# Generated by Django 4.1.5 on 2023-01-06 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_content_task_due_date_time_task_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date_time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
