# Generated by Django 4.1.5 on 2023-01-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_due_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date_time',
            field=models.DateField(),
        ),
    ]
