# Generated by Django 4.1.5 on 2023-01-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_task_date_alter_task_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='time',
            new_name='due_time',
        ),
    ]
