# Generated by Django 4.1.5 on 2023-01-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_remove_task_due_time_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='images',
        ),
        migrations.AddField(
            model_name='task',
            name='attachements',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
