# Generated by Django 4.1.5 on 2023-01-12 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_alter_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.IntegerField(choices=[(0, 'Backend'), (1, 'Frontend'), (2, 'Database'), (3, 'Python'), (4, 'Javascript')], default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
