# Generated by Django 4.1.5 on 2023-02-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_task_category_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
