# Generated by Django 4.1.5 on 2023-03-07 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_task_completed_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='attachements',
            new_name='attachments',
        ),
    ]
