# Generated by Django 4.1.5 on 2023-03-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_rename_attachements_task_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
